"DbUser" = "admindb"
"DbPassword" = "Senha_10"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "srvserviandb.postgres.database.azure.com"
"ListenHost" = "app-serviandemo.azurewebsites.net"
"ListenPort" = "3000"